version: '3.2'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbit-mq
    ports:
    - "5672:5672"
    - "15672:15672"
    - "15692:15692"
    networks:
      - elk
    volumes:
    - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

networks:
  elk:
    driver: bridge